### ISSUE TITLE
Typescript definition file name is spelled incorrectly ...e

### ISSUE THREAD

**Issue by silverfox1948** [orientechnologies/orientjs#202]
I'm trying to  download the typescript definition file for orientjs. "Typings" can't find it to download. I believe it is because the filename is incorrectly spelled. Currently it is:
orinetjs.d.ts    It should be:
orientjs.d.ts

Please fix!

**Comment by saeedtabrizi** [comment]
@silverfox1948 yes . sorry for mistake .

**Comment by saeedtabrizi** [comment]
@silverfox1948  i correct the file name and add some new features too . 
i push it after some tests . 
thanks .

**Comment by saeedtabrizi** [comment]
@silverfox1948  , @maggiolo00 . It was fixed in #233 & #234  merge pull  requests and also updated in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14425 if you running `tsd` or `npm` .

After merge the new pull request you can use `npm install @types/orientjs --save-dev` to install orientjs with updated features .

**Comment by guylichtman** [comment]
If you have the types at: `@types/orientjs`, why do you still have the folder: `typescript/orientjs` ? 

It was a bit confusing for me.

**Comment by saeedtabrizi** [comment]
Hi @guylichtman 
It's a (`typescript/orientjs`) only a mirrored version file for development syncing purpose that you can use or not  . if you prefer to don't using the `@types` repository you can use the internal version of definition file that included with `orientjs` package . 

Some packages in the typescript world using the internal definition file for the ease of use and integration purpose . 
@maggiolo00  we can close this issue as  we already fixed misspelling problem in #234 .
Thanks Saeed Tabrizi .

**Comment by guylichtman** [comment]
Hi @saeedtabrizi , thanks for the clarification.

I also noticed that for function `db.class.create()` the parameter `ifnotexist` is defined as a parameter as part of the typescript definition, but the actual code doesn't deal with this. It looks like this was added as part of #234. And if i understand correctly this hasn't been released yet.

Any idea when this will be released?

**Comment by saeedtabrizi** [comment]
@guylichtman Yes , some functionalities merged but not released yet and planned to orientjs **version 3** as i know . 
If you want to use `if , rollback , sequence` statement in the transactions you can fork and pack your own orientjs offline package .
I'm using my own offline packed version from orientjs forked repository and it's working fine , but i believe the orientjs can be release #234 and #232 related features in the next minor release because `sequence , if , rollback` features is very useful to developers exactly . 
There is some good news in the next major release exactly . at this point and for the conclusion , the release date and feature planning depends to orientjs team decisions . 
If you want to have this features in official package of orientjs , so you can request from (@maggiolo00 , @lvca ) to change their decisions about it . 

There is an open issue in orientdb  to add `ifnotexist` capability to remained schema definition commands in  https://github.com/orientechnologies/orientdb/issues/7529  .
