### ISSUE TITLE
Replace promises with observables

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/orientjs#231]
https://egghead.io/lessons/rxjs-rxjs-observables-vs-promises

I don't think there are any doubts that observables are more powerful, so may I suggest a full replacement of promises around?

Potentially, you could use
`Observable.fromPromise (db..where.one() // .all() /// .scalar())`
But a bit dirty :-)

**Comment by StarpTech** [comment]
Powerful in which cases for orientjs ? Orientjs is database driver.  It consist of parser,  query builder,  connection pool...  components which already compose good without an extra layer. Database driver will be developed with performance in mind. I would prefer to make such features configureable without runtime impact. 

> rxjs is a set of libraries to compose asynchronous and event-based programs using observable collections and Array#extras style composition in JavaScript

**Comment by tiagodavi** [comment]
Promise Vs Observable

1) Promise is always executed when you call it. Observable is Lazy, it just executates when you subscribe to it.

2) Promise can't be canceled. Observable can be canceled at any moment.

3) It just why you use "then" it doesn't mean you are not making callback hell. Promise leads to "then hell".

4) It looks like OrientJS is using BlueBird, a third party library for creating promises. You can replace it for using RxJS and having several functions available instead of having a lot of "then" functions.

**Comment by igasparetto** [comment]
I make mine @tiagodavi 's words

**Comment by StarpTech** [comment]
@tiagodavi 
Promises are part of the nodejs core. I see no problems with Promises if you use them wisely. Rxjs is a powerful tool to handle asynchronous stream of data. After some research I must agree the benefits are great http://stackoverflow.com/questions/37364973/angular-2-promise-vs-observable . I think that would mean a complete rewrite.

**Comment by igasparetto** [comment]
I am happy to take the punch with @tiagodavi

**Comment by StarpTech** [comment]
@igasparetto a driver with streaming support for 3.0 is planned but I dont think that they planned support for observables.

**Comment by igasparetto** [comment]
Worth starting the conversation at this point.

**Comment by maggiolo00** [comment]
Hi Guys

i've played a little bit with Observables in Angular 2 and i like them a lot.
There are two places where they could fit very well in OrientJS

- Live query
- New Streaming protocol of OrientDB 3.0 (OrientJS 3.0)

The first one in case have could be rewritten in order to support Observables

Now it's like

```JS
db.liveQuery("live select from V")
  .on('live-insert', function(data){
     //new record inserted in the database,
     var myRecord = data.content;
     // your code here...
  })
 ...
```

The second one, once the OrientDB 3.0 M1 is out and the protocol is stable enough 
in terms of specs, we will start to implement it and it makes sense to write it using Observables
instead of a custom stream interface.

**Comment by igasparetto** [comment]
Nice one. Would be good to see a namespace for the event names. Perhaps an "o:".

**Comment by saeedtabrizi** [comment]
@maggiolo00 Wow , it's cool . 
Let me to sync the typescript definition file to the latest orientjs features before release the next major version .

**Comment by saeedtabrizi** [comment]
@maggiolo00 Is there any status update  ?

**Comment by maggiolo00** [comment]
Hi  @saeedtabrizi 

yes, i'm working on supporting the new protocol of OrientDB 3.0, that in case of queries the result set is a paginated stream. So probably the Observable is the best choice.
It's not pushed yet since the protocol is not frozen yet. I will ping you when it's ready to be synched with the typescript definition file

**Comment by saeedtabrizi** [comment]
@maggiolo00 it's good news  and i look forward  .

**Comment by saeedtabrizi** [comment]
@lvca, @maggiolo00 is there any update or documentation update for this.

**Comment by maggiolo00** [comment]
Hi @saeedtabrizi 

there is not docs yet. Those are new APIs that are coming with OrientJS 3.0.
I will keep you updated for it

Thanks

**Comment by maggiolo00** [comment]
Unfortunately we fallback to using Node.js Stream, for supporting OrientDB 3.0 paginated result set in OrientJS. We did a benchmark and the overhead created by Observable was to much.

The new version of OrientJS is in beta now with OrientDB 3.0 features

Here it's the release

https://www.npmjs.com/package/orientjs/v/3.0.0-beta.0

and here it's the documentation of the new APIs

https://orientdb.com/docs/last/orientjs/OrientJS-beta.md

**Comment by igasparetto** [comment]
Is that a final decision?

**Comment by maggiolo00** [comment]
@igasparetto 

yes we saw 20-30% of performance decrease Observable vs Node.JS Stream. 
We prefer to not add this performance loss by default for users that do not use Observable.

Maybe we can add it as optional dependency if rx-js is installed?

**Comment by igasparetto** [comment]
Sorry for the delay in replying.
I think that would be an option, but thanks for letting us know.
Thanks
