### ISSUE TITLE
Is the driver (3.0.11) compatible with OrientDB 3.2.x ?

### ISSUE THREAD

**Issue by avery-chung** [orientechnologies/orientjs#449]
As in README (https://github.com/orientechnologies/orientjs/blob/3.0.11/README.md#features), it only claims Tested with latest OrientDB (2.2.x and 3.0.x).

And I see a commit in `develop` branch (https://github.com/orientechnologies/orientjs/commit/cdd45728b28f64dba0c39d6850be6a5ad1516d44) which uses a different config file for OrientDB 3.0.x and 3.1.x , but the change is not yet released.

I would like to ask if the driver (3.0.11) supports OrientDB 3.2.x ?
And is there any plan for maintaining the driver?

**Comment by yoanhuret** [comment]
We also need for this. Any plan ?

Regards,

**Comment by VikramShityalkar** [comment]
I am also planning to upgrade the OrientDB version to 3.2. 

I facing issues with current driver connecting to OrientDB. e.g. Session open with token flag false is not supported anymore please use token based sessions. 

The question is does OrientJS is going to be upgraded to support 3.2? If yes the do we have any documentation that explain how to generate the token and pass it while acquiring sessions.

@wolf4ood could you please let us know if you are still maintaining this repository or anyone from OrientDB team is looking at it.

**Comment by tomByrer** [comment]
Seems forgotten about.... just like their [WiKi](http://orientdb.org/docs/3.1.x/apis-and-drivers/#apis-and-drivers)

**Comment by tglman** [comment]
Hi,

Yes the driver is outdate, it should more or less work, but there are a couple of things that are not compatible any more , first the token authentication is the default now, but if you are using the new API like mentioned here: https://orientechnologies.github.io/docs/3.2.x/orientjs/OrientJS.html should work out of box, another thing is since 3.2.x there are not any more default password, which it means that all the tests of orientjs that use default password do not work any more, so also at your side do not rely on default user and password, are not there.

As today we cannot really maintain this, but I'm happy to review and merge PR, I did add some additional configuration to run the 3.2.x server so it tests are could be run against it, so if anyone is interested can spawn it and see the failing tests,
I feel the two main reason that the test fails are the one mentioned before, there may be additional failures, but first I guess would be easier to tackle the low hanging fruit an  progress from that.

**Comment by tglman** [comment]
Hi,

We did a release with base compatibility updates, the last release works ok with OrientDB 3.2.x, closing this
