### ISSUE TITLE
OrientJS will stop working after upgrading to latest version of NodeJS v18+

### ISSUE THREAD

**Issue by VikramShityalkar** [orientechnologies/orientjs#451]
I was working to upgrade my application latest NodeJS v18LTS as v16 went into matainance mode. The NodeJS introduced "[closed](https://nodejs.org/docs/latest-v18.x/api/stream.html#readableclosed)" on readable stream. This property is getter only. The OResult class has property closed at https://github.com/orientechnologies/orientjs/blob/7b873d60fedf3a42164d2aded7d7860bca2bf47c/lib/client/database/result.js#L13 and at https://github.com/orientechnologies/orientjs/blob/7b873d60fedf3a42164d2aded7d7860bca2bf47c/lib/client/database/result.js#L71 and code trying to set the property. The node 18+ will throw following exception.
``` JavaScript
TypeError: Cannot set property closed of #<Readable> which has only a getter    at new OResult (/usr/src/node_modules/orientjs/lib/client/database/result.js:13:17)    at ODatabaseSession.execStream (/usr/src/node_modules/orientjs/lib/client/database/database.js:102:18)    at ODatabaseSession.query (/usr/src/node_modules/orientjs/lib/client/database/database.js:130:17)
```
Is it possible to adjust the code and publish new package?

@tglman

**Comment by tglman** [comment]
Hi,

I do not really know to handle and fix the problem myself, but anyway I'm happy to review PR and make sure that a new version is published timely.

Regards

**Comment by algoflows** [comment]
Is this DB driver still being supported? Last release was 3 years ago on NPM......

**Comment by Heartnett** [comment]
@wolf4ood @phpnode @tglman @gabipetrovay @ffissore @navinparray @saeedtabrizi will this driver receive any updates in the future to work with OrientDB v3.2.x?

**Comment by tglman** [comment]
Hi,

We managed to update the dependencies, re-enable the CI, and fix the minor compatibility problems with the last release, so we also published an updated release, that should work enough well with the latest version of OrientDB and nodejs.

In terms of future maintenance, the client need a bit of rework to make it more modern, for example use async+await syntax instead of features, I do not think we can handle all the updates from our side, but since now there is a stable base, should not too hard for third party to do some code maintenance and evolution, I will be happy to review and merge changes and handle the release of updated versions.

In any case the current develop branch run correctly with node v18+, closing this.
